/*//GEN-LINE:variables
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop1_9;

import DBConnection.DBConnect;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        this.filterTanggalInput.setVisible(false);
    }
    
    private void initReport() throws Exception {
        DBConnect db = new DBConnect();
        
        JasperDesign jd = JRXmlLoader.load("D:\\Efje\\Kampus\\Semester 4\\OOP 2\\UAS\\src\\iReport\\LaporanPenjualan.jrxml");
        
        JasperReport jr = JasperCompileManager.compileReport(jd);
        
        JasperPrint jp = JasperFillManager.fillReport(jr, null, db.connect());
        
        JasperViewer.viewReport(jp, false);
    }
    
    private void initReport(String filter) throws Exception {
        DBConnect db = new DBConnect();
        
        JasperDesign jd = JRXmlLoader.load("D:\\Efje\\Kampus\\Semester 4\\OOP 2\\UAS\\src\\iReport\\LaporanPenjualan.jrxml");
        
        String sql = "SELECT * FROM sales " +
                "LEFT JOIN products " +
                "ON sales.product_id = products.product_id " +
                "WHERE sales_date = '" + filter + "';";
        
        JRDesignQuery q = new JRDesignQuery();
        
        q.setText(sql);
        jd.setQuery(q);
        
        JasperReport jr = JasperCompileManager.compileReport(jd);
        
        JasperPrint jp = JasperFillManager.fillReport(jr, null, db.connect());
        
        JasperViewer.viewReport(jp, false);
    }
    
    private void cetakLaporan() {
        String format = "YYYY-MM-dd";
        SimpleDateFormat formatter = new SimpleDateFormat(format);
        
        String filter = formatter.format(this.filterTanggalInput.getDate());
        
        System.out.println(filter);
        System.out.println(filter != null);
        
        if (filter != null) {
            try {
                this.initReport(filter);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            try {
                this.initReport();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filterTanggalInput = new com.toedter.calendar.JCalendar();
        cetakLaporanButton = new javax.swing.JButton();
        navigateToPOS = new javax.swing.JButton();
        toggleFilterTanggalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Filter Tanggal");

        cetakLaporanButton.setText("Cetak Laporan");
        cetakLaporanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakLaporanButtonActionPerformed(evt);
            }
        });

        navigateToPOS.setText("Kembali");
        navigateToPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigateToPOSActionPerformed(evt);
            }
        });

        toggleFilterTanggalButton.setText("Filter Tanggal");
        toggleFilterTanggalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleFilterTanggalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cetakLaporanButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(navigateToPOS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toggleFilterTanggalButton)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(filterTanggalInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toggleFilterTanggalButton)
                .addGap(18, 18, 18)
                .addComponent(filterTanggalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cetakLaporanButton)
                    .addComponent(navigateToPOS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void navigateToPOSActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        pointOfSale pos = new pointOfSale();
        pos.setVisible(true);
        pos.pack();
        pos.setLocationRelativeTo(null);
        this.dispose();
    }                                             

    private void cetakLaporanButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:        
        this.cetakLaporan();
    }                                                  

    private void toggleFilterTanggalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
        String status = this.toggleFilterTanggalButton.getText();
        String text = status == "Tutup" ? "Filter Tanggal" : "Tutup";
        
        this.filterTanggalInput.setVisible(!"Tutup".equals(status));

        this.toggleFilterTanggalButton.setText(text);
    }                                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cetakLaporanButton;
    private com.toedter.calendar.JCalendar filterTanggalInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton navigateToPOS;
    private javax.swing.JButton toggleFilterTanggalButton;
    // End of variables declaration                   
}
